# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='http.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nhttp.proto\"\x1b\n\x0bHttpRequest\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x1e\n\x0cHttpResponse\x12\x0e\n\x06result\x18\x01 \x02(\t22\n\x0bHttpService\x12#\n\x04\x45\x63ho\x12\x0c.HttpRequest\x1a\r.HttpResponse'
)




_HTTPREQUEST = _descriptor.Descriptor(
  name='HttpRequest',
  full_name='HttpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='HttpRequest.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=41,
)


_HTTPRESPONSE = _descriptor.Descriptor(
  name='HttpResponse',
  full_name='HttpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='HttpResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['HttpRequest'] = _HTTPREQUEST
DESCRIPTOR.message_types_by_name['HttpResponse'] = _HTTPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HttpRequest = _reflection.GeneratedProtocolMessageType('HttpRequest', (_message.Message,), {
  'DESCRIPTOR' : _HTTPREQUEST,
  '__module__' : 'http_pb2'
  # @@protoc_insertion_point(class_scope:HttpRequest)
  })
_sym_db.RegisterMessage(HttpRequest)

HttpResponse = _reflection.GeneratedProtocolMessageType('HttpResponse', (_message.Message,), {
  'DESCRIPTOR' : _HTTPRESPONSE,
  '__module__' : 'http_pb2'
  # @@protoc_insertion_point(class_scope:HttpResponse)
  })
_sym_db.RegisterMessage(HttpResponse)



_HTTPSERVICE = _descriptor.ServiceDescriptor(
  name='HttpService',
  full_name='HttpService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=75,
  serialized_end=125,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='HttpService.Echo',
    index=0,
    containing_service=None,
    input_type=_HTTPREQUEST,
    output_type=_HTTPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HTTPSERVICE)

DESCRIPTOR.services_by_name['HttpService'] = _HTTPSERVICE

# @@protoc_insertion_point(module_scope)
